export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_COLUMNS_BUTTON_ANCHOR_ELEMENT =
  'SET_COLUMNS_BUTTON_ANCHOR_ELEMENT';
export const SET_EXPORT_BUTTON_ANCHOR_ELEMENT =
  'SET_EXPORT_BUTTON_ANCHOR_ELEMENT';
